<?php

/**
 * Implementatie van hook_block_info - declaring blocks
 *
 * @return array  $blocks   The declared blocks
 */
function twompact_login_block_info() {
  $blocks['login_loggedin_box'] = array(
    'info' => t('Logged in box'),
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view - giving content to blocks
 *
 * @param string $delta     The delta of the block we wish to render
 * @return array $block     The block we wish to render
 */
function twompact_login_block_view($delta = '') {
  switch($delta) {
    case 'login_loggedin_box':
      $block = array(
        'subject' => '',
        'content' => twompact_login_loggedin_box(),
      );
      break;
  }

  return $block;
}

/**
 * Creates a simple block with some options for logged in users
 */
function twompact_login_loggedin_box() {
  global $user;
  global $language;
  $taal = $language->language;

  $welcome = t('Welcome @username.');

  // contact gekoppeld aan user ophalen
  if(module_exists('civicrm')) {
    civicrm_initialize();

    $cid = db_select('civicrm_uf_match', 'cu')
      ->fields('cu', array('contact_id'))
      ->condition('uf_id', $user->uid)
      ->execute()
      ->fetchField();

    try {
      $contact = civicrm_api3('Contact', 'getsingle', array(
        'sequential' => 1,
        'id' => $cid,
      ));

      $profiel_link = '<a href="/profiel">' . t('Keep your profile up-to-date') . '</a>';
      $picture = '';
      $percentage = twompact_login_profile_completion_calculation($contact);
      $profile_percentage = '<p>' . t('Profile') . ' <span class="percentile">' . $percentage . '%</span> ' . t('complete') . '</p>';

      if(!empty($contact['first_name']) || !empty($contact['last_name'])) {
        $welcome = str_replace('@username', $contact['first_name'] . ' ' . $contact['last_name'], $welcome);
      }
      else {
        $welcome = str_replace('@username', $user->name, $welcome);
      }
    }
    catch(CiviCRM_API3_Exception $e) {
      watchdog('twompact login', $e->__toString());

      $profiel_link = '<a href="/user/' . $user->uid . '/edit">' . t('Change your login data') . '</a>';
      $welcome = str_replace('@username', $user->name, $welcome);
      $profile_percentage = '';
    }
  }
  else {
    $profiel_link = '<a href="/user/' . $user->uid . '/edit">' . t('Change your login data') . '</a>';
    $welcome = str_replace('@username', $user->name, $welcome);
    $profile_percentage = '';
  }

  $result = '';

  if(user_is_logged_in()) {
    $linktaal = '/' . $taal;
    $extranet_link = '<a href="' . $linktaal . '/extranet">' . t('Go to the extranet') . '</a>';

    $result =<<<STR
<div class="logged_in_box">
  <div class="profile_links">
    <p>
      $welcome $profiel_link
      <br />
      $extranet_link
    </p>
  </div>
  <div class="profile_rechts">
    <!--<div class="profile_picture">$picture</div>-->
    <div class="profile_percentage">$profile_percentage</div>
  </div>
</div>
<div class="clear">&nbsp;</div>
STR;
  }

  return $result;
}

function twompact_login_profile_completion_calculation($contact = NULL) {
  global $user;

  if(is_null($contact)) {
    return '0';
  }
  else {
    // we bepalen hoeveel informatie het contact reeds heeft ingevuld.  Het contact krijgen we mee als functie argument
    // maar we zullen nog een paar api calls moeten doen om te bepalen of er een telefoon en primair adres is ingegeven
    $tmp_result = 0;
    $result = 0;

    // standaard contact velden
    $contact_velden = array(
      'first_name',
      'last_name',
      'email',
      'gender_id',
      'phone',
      'street_address',
      'city',
      'postal_code',
    );

    if(!empty($contact_velden) && is_array($contact_velden)) {
      foreach($contact_velden as $tmp_idx => $veldnaam) {
        if(!empty($contact[$veldnaam])) {
          $tmp_result += 1;
        }
      }
    }

    // bepalen hoeveel percent we ingevuld hebben gebaseerd op het totaal aantal velden dat gecontroleerd wordt
    if($tmp_result != 0) {
      $totaal_aantal_velden = count($contact_velden);

      // percentage berekenen
      $result = ceil((100 / $totaal_aantal_velden) * $tmp_result);
    }
    else {
      $result = 0;
    }
  }

  return $result;
}